// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTodoInput struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type DeleteTodoInput struct {
	ID int `json:"id"`
}

type UpdateTodoInput struct {
	ID     int     `json:"id"`
	Text   *string `json:"text"`
	IsDone *bool   `json:"isDone"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
